### ISSUE TITLE
Additions to how this package fits into the existing R ecosystem

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/punisheR#31]
Other packages that do forward and backward (and best subset) selection:
- [leaps](https://cran.r-project.org/web/packages/leaps/leaps.pdf)
- [bestglm](https://cran.r-project.org/web/packages/bestglm/bestglm.pdf)

Also, can you clarify what you mean by  "p-value-based methods of feature selection". P-values of what?

Finally, I think you should highlight how your package does more (e.g., BIC) or different things than these other packages. Think of selling users on why to use your package.

**Comment by TariqAHassan** [comment]
@ttimbers 

Is it required that our package implement novel capabilities? For instance, I recall being told that last year a group implemented standard linear regression and that was fine.

**Comment by ttimbers** [comment]
No, novelty is not required but a clear description of overlap (and novelty if it exists) is required.

**Comment by avinashkz** [comment]
* Changes made to fix the issues addressed are highlighted in bold below.

## How does the package fit into the existing R ecosystem?

In the R ecosystem, the forward and backward selection is implemented in both the [olsrr](https://cran.r-project.org/web/packages/olsrr/) and [MASS](https://cran.r-project.org/web/packages/MASS/MASS.pdf) packages. The former provides [`ols_step_forward()`](https://www.rdocumentation.org/packages/olsrr/versions/0.4.0/topics/ols_step_forward) and [`ols_step_backward()`](https://www.rdocumentation.org/packages/olsrr/versions/0.4.0/topics/ols_step_backward) for forward and backward stepwise selection, respectively. Both of these use p-value as a metric for feature selection. The latter, MASS, contains [`StepAIC()`](https://stat.ethz.ch/R-manual/R-devel/library/MASS/html/stepAIC.html), which is complete with three modes: forward, backward or both. The selection procedure it uses is based on an information criterion (AIC), as we intend ours to be. **Other packages that provide subset selection for regression models are [leaps](https://cran.r-project.org/web/packages/leaps/leaps.pdf) and [bestglm](https://cran.r-project.org/web/packages/bestglm/bestglm.pdf).**

**In `punisheR`, users can select between criterions such as `aic`, `bic` and `r-squared` for forward and backward selections. Also, the number of features returned by these selection algorithms can be specified by using `n_features` or by using `min_change`; users can specify the minimum change in the criterion score for an additional feature to be selected.**
