### ISSUE TITLE
Function documentation incomplete

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/punisheR#33]
In both the function docs in the `.R` files and in the README it is not clear what your functions return. Is it a model object from `forward` and `backward`? Is it a single value of type double from `AIC` and `BIC`? Something else? Please add to the docs to clarify.

**Comment by ttimbers** [comment]
I see that at least there are Value docs for `AIC` & `BIC`, but they are not there for `forward` and `backward`.

**Comment by ttimbers** [comment]
Also, in `forward` and `backward` docs does `n_features`, defined as Number of features to allow, mean the maximum number of features to allow or something different? Please clarify in your docs.

**Comment by ttimbers** [comment]
Also, in `forward` and `backward` docs the only examples of `criterion` listed are `"aic"` and `"bic"`, yet your vignette uses `"r-squared"`. Thus, you should _at least_ also list `"r-squared"` as an example in the docs. Are there other valid strings for the `criterion` argument? If so, make sure you list these too.

**Comment by topspinj** [comment]
Hi Tiffany, our forward and backward functions do have `@return` descriptions:
backward.R line 37
https://github.com/UBC-MDS/punisheR/blob/master/R/backward.R#L37
forward.R line 18
https://github.com/UBC-MDS/punisheR/blob/master/R/forward.R#L18

Re: showing examples of aic/bic criterion, we actually haven't documented that part yet so I'm surprised that examples are being shown! We will do this in Milestone 3 and will make sure that vignette and documentation align.

**Comment by ttimbers** [comment]
>Hi Tiffany, our forward and backward functions do have @return descriptions:
backward.R line 37
https://github.com/UBC-MDS/punisheR/blob/master/R/backward.R#L37
forward.R line 18
https://github.com/UBC-MDS/punisheR/blob/master/R/forward.R#L18

Great! All my comments are regarding the milestone2 version. So you're doing the exact right thing. Document that you have addressed these issues in this thread. And when you've fully addressed it (e.g., the aic/bic stuff) document it (you can link to the commit by just pasting in the commit id, or it will automatically show up by tagging this issue in the commit message once you push the commit) and then close the issue 😃

**Comment by ttimbers** [comment]
Add: "At least one of `n_features` and `min_change` must be NULL" to the function docs. Currently they are only written in the tests for the functions.
