### ISSUE TITLE
Why require matrix and vectors as input for `forward` and `backward` functions?

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/punisheR#34]
Why require matrix and vectors (you should use this term in the R docs, not array) as input for `forward` and `backward` functions? Users often load datasets into R using `read_*` or `read.*` and the object returned from these functions is a data frame. So by requiring your users to convert to matrix and vectors each time this will create a lot of code redundancy for your users. I suggest you do one of the following:
- allow users to also give your function a dataframe for `X_train`, `y_train`, `X_val`, `y_val` and write the conversion to matrix and vector into your function if they do indeed pass your function a dataframe, OR
-write a function that takes a dataframe and based on arguments provided by the user gives you back `X_train`, `y_train`, `X_val`, `y_val` in the types your `forward` and `backward` functions currently require.

**Comment by topspinj** [comment]
Our intention was to mirror the functionality of PyPunisher, which currently takes in X and y as 2D and 1D arrays respectively. We will have our functions handle dataframes in our next release.
