### ISSUE TITLE
no explanation of what the `test_data` function does in vignette

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/punisheR#37]
It is difficult to follow your vignette because there is no clear explanation of what `test_data` function does in vignette. Code comments or narration above its creation and use would greatly help.

**Comment by avinashkz** [comment]
<img width="535" alt="screen shot 2018-03-16 at 8 10 00 pm" src="https://user-images.githubusercontent.com/21602046/37551082-205f3e7e-2956-11e8-9238-a8e86c8486e8.png">
<img width="356" alt="screen shot 2018-03-16 at 8 09 31 pm" src="https://user-images.githubusercontent.com/21602046/37551084-24e1adb0-2956-11e8-8692-77eca1c5f4e9.png">

Added comments in the vignette.
