### ISSUE TITLE
`covr` suggests you are not at 100% branch coverage

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/punisheR#39]
When running `covr::report()` it suggests you are not at 100% branch coverage:

<img width="945" alt="screen shot 2018-03-15 at 9 00 09 pm" src="https://user-images.githubusercontent.com/6865016/37503198-27b2bb5a-2894-11e8-9a9c-496abbeb74a3.png">

Install the [`covr`](https://github.com/r-lib/covr) package and do this yourself - then when you get this table, click on the filenames in the File column for more information where you could be missing coverage.

**Comment by topspinj** [comment]
The current version of our code has `covr` implemented. You can see the badge in our readme:
https://github.com/UBC-MDS/punisheR/blob/master/README.md
