### ISSUE TITLE
Better test for values from AIC & BIC

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/punisheR#43]
The current test for testing the values returned by your `AIC` & `BIC` functions are this:
```
test_that("test_metric_output_value", {
    # Test that the actual AIC and BIC values computed by
    # our functions match that computed by Base R.
    expect_equal(aic(model), AIC(model))
    expect_equal(bic(model), BIC(model))
```
This is not ideal because what if the Base R functions are wrong or have bugs? This method of testing will just propagate them into your code base. You should test simpler cases for your AIC & BIC functions where the math is simple enough you can do it by hand (`lm` with 2 or 3 observations maybe?).

**Comment by TariqAHassan** [comment]
@ttimbers 

I am not sure how we should proceed as we already implemented our `aic()` and `bic()` functions 'by hand'. Thus, we were to check our own code by writing more code 'by hand', it seems that we'd be acting as both the implementors and the examiners of our own understanding of AIC and BIC. 

As you know, both `AIC` and `BIC` are implemented in the `stats` library in R, which is quite old. After some digging, I was able to find AIC's and BIC's source [here](https://github.com/wch/r-source/blame/af7f52f70101960861e5d995d3a4bec010bc89e6/src/library/stats/R/AIC.R) -- the former is over a 15 years old. Thus, it has no doubt been more throughly tested than our own understanding of how to compute these values.

**Comment by ttimbers** [comment]
>Thus, it has no doubt been more throughly tested than our own understanding of how to compute these values.

Are there tests for the Base R's AIC & BIC functions? There might not be... Never trust code unless you see tests.

>Thus, we were to check our own code by writing more code 'by hand', it seems that we'd be acting as both the implementors and the examiners of our own understanding of AIC and BIC

This is the case for any code we write. Just pick a simple `lm` case (e.g., 3 observations) and do your best.

**Comment by TariqAHassan** [comment]
@ttimbers 

Sorry. I'm still confused here. Would you like us to run OLS by hand?

**Comment by ttimbers** [comment]
Yes.

**Comment by TariqAHassan** [comment]
@ttimbers 

How is that reproducible though?

**Comment by TariqAHassan** [comment]
Moreover, we're not interrogating the logic of `lm` here. We're interrogating the logic of our AIC and BIC computations. OLS is not within the scope of our project.

**Comment by ttimbers** [comment]
Well you need to calculate AIC, maybe you don't need to do ols exactly. Is there a special case of AIC that you just know? There is for Rsquared - it is 1 when the data fit perfectly...
